title = "heyo"
theme = "heyo-hugo-theme"
#baseURL = "/"
baseURL = "https://baigel2.github.io/pob-testing/"
languageCode = "en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
summarylength = 100
enableEmoji = true
enableRobotsTXT = true
pagination.pagerSize = 10

# Disqus comments
# https://gohugo.io/templates/internal/#configure-disqus
# disqusShortname = ""

# Google Analytics
# https://gohugo.io/templates/internal/#google-analytics
# googleAnalytics = ""

[params.author]
    name = "Jane Doe"
    email = "jane@doe.com"

[params]
    title = "I'm Jane Doe"
    description = "Call me Jane"
    profilePicture = "images/colouredQuran.png"
    favicon = "favicons/"
    customCss = []
    customJs = []
    displayMode = "light"
    images = ['images/profile.png']

[taxonomies]
    series = 'series'
    categories = 'categories'
    tags = 'tags'

# Sketch settings
# you can also enable or disable it per page
[params.sketch] 
    enable = true 
    displayOptions = false
    # Graph, Digital Rain, or Circles
    use = "Circles"
    # JSON that is passed to the sketch constructor
    # You can check all the possible configurations in
    startingConfig = """{
        "kind": "katakana",
        "nStreams": 10
    }"""

## Math settings
[params.math]
    enable = true # global support, you can also configure it per page
    use = "mathjax" # katex or mathjax, default is mathjax

## Social links
[[params.socialIcons]]
icon = "fab fa-linkedin" # Font-awesome icon
title = "Linkedin"
url = "https://linkedin.com/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/LucasVadilho/heyo-hugo-theme"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:lucas.vadilho@gmail.com"

[languages]
    [languages.en]
        languageCode = "en"
        contentDir = "content/en"
        weight = 1
        languageName = "en"
        [languages.en.menus]
            [[languages.en.menus.main]]
                name = "Home"
                pageRef = "/"
                weight = 1
            [[languages.en.menus.main]]
                name = "Posts"
                pageRef = "en/post"
                weight = 3
            [[languages.en.menus.main]]
                name = "About"
                pageRef = "/about"
                weight = 2

[markup]
    [markup.goldmark.renderer]
        unsafe = true
    [markup.tableOfContents]
        endLevel = 6
        startLevel = 1
    [markup.highlight]
        anchorLineNos = false
        codeFences = true
        guessSyntax = false
        hl_Lines = ""
        lineAnchors = ""
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        noClasses = true
        style = "dracula"
        tabWidth = 4

# Hugo will ignore these files, .rmd and .rmarkdown are taken care by blogdown
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown", "_files$", "_cache$"]
